name: Mathicorn
description: A fun math practice app for elementary school students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  audioplayers: ^6.5.0
  flutter_animate: ^4.2.0+1
  provider: ^6.1.1
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
    - assets/images/mathicorn.png
    - assets/animations/
    - .env
