name: Mathicorn
description: A fun math practice app for elementary school students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  audioplayers: ^6.5.0
  flutter_animate: ^4.2.0+1
  provider: ^6.1.1
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  lottie: ^3.1.0
  fl_chart: ^1.0.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
    - assets/images/mathicorn.png
    - assets/animations/
    - .env
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mathicorn_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/mathicorn_icon.png"
    background_color: "#8B5CF6"
    theme_color: "#8B5CF6"
  windows:
    generate: true
    image_path: "assets/images/mathicorn_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/mathicorn_icon.png"